# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - install
  - test
  - package
  - publish
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - redis:latest
  - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
    - node_modules/

.test:
  before_script:
    - echo "Hello" > file1.txt
    - echo "world" > file2.txt
  stage: test
  script: 
    - echo "Testing"

.package:
  stage: package
  before_script:
    - echo "Packing module"
  script:
    - echo "We just packed the module succesfully"
  artifacts:
    paths:
      - package.gz

publish:
  stage: publish
  before_script:
    - yarn global add --silent semantic-release@16.0.4
  script:
    - semantic-release
